-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS AccountGroup CASCADE;
DROP TABLE IF EXISTS Message CASCADE;
DROP TABLE IF EXISTS Topic CASCADE;
DROP TABLE IF EXISTS Group CASCADE;
DROP TABLE IF EXISTS Account CASCADE;